import os
from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
list = os.listdir(cwd)

CPPPATH = [cwd, str(Dir('#'))]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
