from building import *

cwd  = GetCurrentDir()
src  = Split('''
board.c
drv_clock.c
drv_uart.c
drv_pin.c
drv_watchdog.c
''')

list = os.listdir(cwd)
CPPPATH = [cwd, cwd+'/hi3516ev200']
objs = []

group = DefineGroup('Drivers', src, depend = [''], CPPPATH = CPPPATH)

for d in list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))
objs = objs + group
Return('objs')
